### ISSUE TITLE
Not an issue but a query

### ISSUE THREAD

**Issue by ck-australia** [xmacan/plugin_snver#9]
Where does this plugin store the data, I can get the data but does it store it anyplace to reference

**Comment by xmacan** [comment]
plugin_snver_history

**Comment by ck-australia** [comment]
Does the host_id match the host_id from cacti and it seems to not be the case, have loads of data in that table but cant seems to work out which device is what, I have 1000 devices in my Cacti install

**Comment by xmacan** [comment]
yes, host.id = plugin_snver_history.host_id

Try query:
select h.description, s.host_id from plugin_snver_history as s left outer join host as h on s.host_id = h.id;

You shouldn't see null in the first columns. If there is null it means that you really have problem. It could be deleted devices
